== IsyFact jQAssistant Plugin

Dieses Plugin enthält Architekturregeln und Programmierkonventionen der IsyFact in Form von Regeln für jQAssistant.

=== Verwendung

Um den Regelsatz zu verwenden wird in der Anwendung ein zusätzliches Maven-Plugin eingerichtet:

[source,xml]
----
<plugin>
    <groupId>com.buschmais.jqassistant</groupId>
    <artifactId>jqassistant-maven-plugin</artifactId>
    <version>${jqassistant.version}</version>
    <executions>
        <execution>
            <id>default-cli</id>
            <goals>
                <goal>scan</goal>
                <goal>analyze</goal>
            </goals>
            <configuration>
                <ruleParameters>
                    <rootPackage>ROOT-PACKAGE-DER-ANWENDUNG</rootPackage>
                </ruleParameters>
                <groups>
                    <group>
                        isyfact:Verbindlich
                    </group>
                    <group>
                        isyfact:Empfohlen
                    </group>
                </groups>
                <!--continueOnError>true</continueOnError-->
            </configuration>
        </execution>
    </executions>
    <dependencies>
        <dependency>
            <groupId>de.bund.bva.isyfact</groupId>
            <artifactId>isyfact-jqassistant-plugin</artifactId>
            <version>1.6.0</version>
        </dependency>
    </dependencies>
</plugin>
----

Im Abschnitt `groups` können Untermengen der Regeln ausgewählt werden.
Folgende Gruppen sind verfügbar:

.Regelgruppen für die IsyFact
[options="header"]
|====
2+| *isyfact:Verbindlich*                                                               2+| *isyfact:Empfohlen*
  | isyfact:batch:Verbindlich         | _AusfuehrungsBeanDarfKeineTransaktionStarten_     | isyfact:batch:Empfohlen            | _BatchklassenMitPraefixBat_
  | isyfact:core:Verbindlich          | _BeanNichtPerNameAuslesen_                        | isyfact:core:Empfohlen             | _GeschaeftsobjektMitBoSuffix_
  | isyfact:datetime:Verbindlich      | _AufrufVonNowOderCurrentTimeMillis_               |                                    |
  |                                   |                                                   | isyfact:fehlerbehandlung:Empfohlen | _ExceptionsErbenVonPlisException_, _ServiceExceptionErbtVonPlisToException_
  |                                   |                                                   | isyfact:gui:Empfohlen              | _ModelBeanSerializable_, _ModelBeanVerwendetAwkTypen_, _ModelBeanNameEnthaeltKomponente_, _ControllerBeanNameEnthaeltKomponente_, _ControllerBeanErbtVonAbstractGuiController_
  | isyfact:konfiguration:Verbindlich | _BenutzeKeineInternenKlassen_                     | isyfact:konfiguration:Empfohlen    | _SpeichereKeineKonfigurationsParameter_
  | isyfact:layer:Verbindlich         | _ZugriffAufCoreLayerUeberInterface_,
                                        _UndefinedDependencies_,
                                        _UnusedDependencies_                              |                                    |
  | isyfact:logging:Verbindlich       | _IsyLoggerMussVerwendetWerden_,
                                        _IsyLoggerMussStatischInitialisiertWerden_,
                                        _IsyLoggerMustBeDeclaredAsConstant_               |                                    |
  | isyfact:package :Verbindlich       | _AlleJavaKlassenMuessenImWurzelPackageLiegen_,
                                        _WurzelPackageUndMavenKoordinatenStimmenUeberein_ |                                    |
  |                                   |                                                   | isyfact:persistence:Empfohlen      | _EntitiesLiegenInPackageEntity_,
                                                                                                                                 _EntitiesVerwendenKeineCompositeKeys_,
                                                                                                                                 _DaoInterfacesVonDaoAbgeleitet_,
                                                                                                                                 _DaoKlasseVonAbstractDaoAbgeleitet_,
                                                                                                                                 _KeineNamedQueriesUeberAnnotationen_,
                                                                                                                                 _KeineBulkQueries_,
                                                                                                                                 _GenerationTypeAuto_,
                                                                                                                                 _KeinePlisDataSource_
  | isyfact:service:Verbindlich      | _ExceptionAnServiceSchnitstelle_,
                                       _ServiceSchnitstelleMitLoggingKontext_,
                                       _ServiceMethodenEnthaltenAufrufKontext_            |                                    |
  |                                  |                                                    | isyfact:ueberwachung:Empfohlen     | _MBeanSuffix_,
                                                                                                                                 _MBeanMitZugriffAufAWK_,
                                                                                                                                 _MBeanPackageStruktur_
|====


